sudo: 'required'
services:
  - 'docker'
language: node_js
node_js:
  - 12.10.0
  - 10.16.3
branches:
  only:
    - master
before_script:
  - npm install
  - npm install -g gulp
script:
  - gulp test
  - gulp coveralls
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker build -t gymmanager . ;
      docker push i4vk/gymmanager ;
    fi
