sudo: 'required'
services:
  - 'docker'
language: node_js
node_js:
  - 12.10.0
  - 10.16.3
branches:
  only:
    - master
before_script:
  - npm install
  - npm install -g gulp
script:
  - gulp test
  - gulp coveralls
deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && bash docker_push.sh
  on:
    branch: master
