---
# Tareas sobre la máquina GymManager
- hosts: GymManager
  # Ajustamos el intérprete de ansible como python3
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  # Damos permisos de superusuario
  become: yes
  tasks:
    # Descargamos un script para instalar node en los repositorios de ubuntu
    - name: Descargar node
      get_url: 
        url: https://deb.nodesource.com/setup_10.x
        dest: /tmp/node.sh

    # Instalamos node en los repositorios de ubuntu
    - name: Instalar node en los repositorios
      command: bash /tmp/node.sh

    # Hacemos un update de los paquetes con apt
    - name: Actualiza lista de paquetes apt
      apt:
        update_cache: yes

    # Instalamos git
    - name: Instala git
      apt: 
        name: git

    # Instalamos node 10
    - name: install nodejs
      apt: 
        name:
          - nodejs

    # Instalamos gulp globalmente
    - name: Instalar gulp
      npm:
        name: gulp
        global: yes

    # Instalamos pm2 globalmente
    - name: Instalar pm2
      npm:
        name: pm2
        global: yes

    # Clonamos el repositorio de nuestra aplicación desde Github
    - name: Clonar repositorio de la aplicación
      git:
        repo: https://github.com/i4vk/GymManager
        dest: /home/vagrant/GymManager
        force: yes

    # Instalamos dependencias propias de la aplicación
    - name: Instalar dependencias de la aplicación
      command: npm install
      args:
        chdir: /home/vagrant/GymManager

    # Arrancamos la aplicación en segundo plano
    - name: Arrancar la aplicación
      shell: gulp start &
      args:
        chdir: /home/vagrant/GymManager